CurrentDesk/CurrentDesk.BackOffice/Models/CorporateAccountReviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurrentDesk.BackOffice.Models
{
    public class CorporateAccountReviewModel
    {       
        
        public string CompanyName { get; set; }        
        public string  CompanyType { get; set; }        
        public string CompanyAddLine1 { get; set; }
        public string CompanyAddLine2 { get; set; }        
        public string CompanyCity { get; set; }        
        public string  CompanyCountry { get; set; }        
        public string CompanyPostalCode { get; set; }
        public string ClientAccountNumber { get; set; }
        public string PhoneID { get; set; }

        //Authorized Officer        
        public string AuthOfficerTitle { get; set; }        
        public string AuthOfficerFirstName { get; set; }
        public string AuthOfficerMiddleName { get; set; }        
        public string AuthOfficerLastName { get; set; }        
        public string AuthOfficerDobMonth { get; set; }
        public string AuthOfficerDobDay { get; set; }        
        public int AuthOfficerDobYear { get; set; }
        public string AuthOfficerGender { get; set; }
        public string AuthOfficerCitizenship { get; set; }
        public string AuthOfficerIdInfo { get; set; }        
        public string AuthOfficerIdNumber { get; set; }        
        public string  AuthOfficerResidenceCountry { get; set; }

        //Authorized Officer Contact Information        
        public string AuthOfficerAddLine1 { get; set; }
        public string AuthOfficerAddLine2 { get; set; }        
        public string AuthOfficerCity { get; set; }        
        public string AuthOfficerCountry { get; set; }        
        public string AuthOfficerPostalCode { get; set; } 
        public long AuthOfficerTelNumberCountryCode { get; set; } 
        public long AuthOfficerTelNumber { get; set; }
        public long AuthOfficerMobileNumberCountryCode { get; set; }
        public long AuthOfficerMobileNumber { get; set; }
        public string AuthOfficerEmailAddress { get; set; }
        public string AuthOfficerConfirmEmailAddress { get; set; }

        //Banking Information       
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string BicOrSwiftCode { get; set; }
        public string BankAddLine1 { get; set; }
        public string BankAddLine2 { get; set; }
        public string ReceivingBankInfoId { get; set; }
        public string ReceivingBankInfo { get; set; }
        public string BankCity { get; set; }
        public string BankCountry { get; set; }
        public string BankPostalCode { get; set; }

        //List Of Bank Account
        public List<BankAccountModel> BankAccountModelList { get; set; }

        //Financial Information 
        public string EstimatedAnnualIncome { get; set; }
        public string LiquidAssets { get; set; }
        public string NetWorthEuros { get; set; }

        //Trading Experience 
        public string DrpHaveExperienceTradingSecurities { get; set; }
        public string DrpHaveExperienceTradingOptions { get; set; }
        public string DrpHaveExperienceTradingForeignExchange { get; set; }

        //Other Information
        public string HaveAccWithFqSecurities { get; set; }
        public string RequiredToBeRegisteredWithRegulator { get; set; }
        public string EverDeclaredBankruptcy { get; set; }
        public string RegisteredPerson { get; set; }
        public string EmployeeOfExchangeOrRegulatorOperator { get; set; }

        public CorporateAccountModel CorporateModel { get; set; }
        public bool IsLive { get; set; }
    }
}

CurrentDesk/CurrentDesk.BackOffice/Models/IndividualAccountReviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CurrentDesk.BackOffice.Models
{
    public class IndividualAccountReviewModel
    {       
        public string Title { get; set; }        
        public string FirstName { get; set; }
        public string MiddleName { get; set; }        
        public string LastName { get; set; }       
        public string DobMonth { get; set; }
        public string DobDay { get; set; }        
        public int DobYear { get; set; }        
        public string  Gender { get; set; }        
        public string  Citizenship { get; set; }        
        public string  IdInfo { get; set; }       
        public string IdNumber { get; set; }
        public string ResidenceCountry { get; set; }
        public string ClientAccountNumber { get; set; }
        public string PhoneID { get; set; }
        public string ResidentialAddLine1 { get; set; }
        public string ResidentialAddLine2 { get; set; }
        public string ResidentialCity { get; set; }
        public string ResidentialCountry { get; set; }
        public string ResidentialPostalCode { get; set; }
        public int YearsInCurrentAdd { get; set; }        
        public int MonthsInCurrentAdd { get; set; }
        public string PreviousAddLine1 { get; set; }
        public string PreviousAddLine2 { get; set; }
        public string PreviousCity { get; set; }
        public string  PreviousCountry { get; set; }
        public string PreviousPostalCode { get; set; }
        public long TelNumberCountryCode { get; set; }
        public long TelNumber { get; set; }
        public long MobileNumberCountryCode { get; set; }
        public long MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string ConfirmEmailAddress { get; set; }

        //Bank Information
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public string BicOrSwiftCode { get; set; }
        public string BankAddLine1 { get; set; }
        public string BankAddLine2 { get; set; }
        public string ReceivingBankInfoId { get; set; }
        public string ReceivingBankInfo { get; set; }
        public string BankCity { get; set; }
        public string BankCountry { get; set; }
        public string BankPostalCode { get; set; }

        //List Of Bank Account
        public List<BankAccountModel> BankAccountModelList { get; set; }

        //Financial Information
        public string EstimatedAnnualIncome { get; set; }
        public string LiquidAssets { get; set; }
        public string NetWorthEuros { get; set; }

        //Trading Experience
        public string DrpHaveExperienceTradingSecurities { get; set; }
        public string DrpHaveExperienceTradingOptions { get; set; }
        public string DrpHaveExperienceTradingForeignExchange { get; set; }

        //Other Information
        public string HaveAccWithFqSecurities { get; set; }
        public string RequiredToBeRegisteredWithRegulator { get; set; }
        public string EverDeclaredBankruptcy { get; set; }
        public string RegisteredPerson { get; set; }
        public string EmployeeOfExchangeOrRegulatorOperator { get; set; }

        public IndividualAccountModel IndividualModel { get; set; }
        public bool IsLive { get; set; }
    }
}

CurrentDesk/CurrentDesk.BackOffice/Controllers/AccountSignUpController.cs
/* **************************************************************
* File Name     :- AccountSignUpController.cs
* Author        :- Mukesh Nayak
* Copyright     :- Mindfire Solutions 
* Date          :- 2nd Jan 2013
* Modified Date :- 16th April 2013
* Description   :- This file will deal with all the 
                   operation related to all the account signup(live trust individual corporate)
****************************************************************/


#region Namespace
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CurrentDesk.BackOffice.Extension;
using CurrentDesk.BackOffice.Models;
using CurrentDesk.Common;
using CurrentDesk.Models;
using CurrentDesk.Repository.CurrentDesk;
using CurrentDesk.BackOffice.Security;
using CurrentDesk.BackOffice.Models.Error;
using CurrentDesk.Logging;
using CurrentDesk.BackOffice.Utilities;
#endregion

namespace CurrentDesk.BackOffice.Controllers
{
    /// <summary>
    /// Account sign up controller
    /// This Controller is responsible for all sign Up
    /// </summary>
    public class AccountSignUpController : Controller
    {
        #region Variables

        private L_CountryBO countryBO = new L_CountryBO();
        private AccountTypeBO accountTypeBO = new AccountTypeBO();
        private L_InitialInvestmentBO initialInvestmentBO = new L_InitialInvestmentBO();
        private TradingPlatformBO tradingPlatformBO = new TradingPlatformBO();
        private L_TicketSizeBO ticketSizeBO = new L_TicketSizeBO();
        private AccountCurrencyBO accountCurrencyBO = new AccountCurrencyBO();
        private L_LanguagesBO languageBO = new L_LanguagesBO();
        private L_AccountCodeBO accountCodeBO = new L_AccountCodeBO();
        private DemoLeadBO demoLeadBO = new DemoLeadBO();
        private L_IDInformationTypeBO idInfoTypeBO = new L_IDInformationTypeBO();
        private L_RecievingBankBO receivingBankInfoBO = new L_RecievingBankBO();
        private L_AnnualIncomeValueBO annualIncomeValuesBO = new L_AnnualIncomeValueBO();
        private L_LiquidAssetsValueBO liquidAssetsValuesBO = new L_LiquidAssetsValueBO();
        private L_NetWorthEurosBO netWorthEurosValuesBO = new L_NetWorthEurosBO();
        private L_TradingExperienceBO tradingExpValuesBO = new L_TradingExperienceBO();
        private L_TrusteeTypeValueBO trusteeTypeValuesBO = new L_TrusteeTypeValueBO();
        private L_CompanyTypeValueBO companyTypeValuesBO = new L_CompanyTypeValueBO();
        private L_CommissionIncrementValueBO commissionIncremantValuesBO = new L_CommissionIncrementValueBO();
        private L_WidenSpreadsValueBO widenSpreadValuesBO = new L_WidenSpreadsValueBO();
        private LiveLeadBO liveLeadBO = new LiveLeadBO();
        private ClientBO clientBO = new ClientBO();
        private UserBO userBO = new UserBO();
        private IndividualAccountInformationBO individualAccountInformationBO = new IndividualAccountInformationBO();
        private CorporateAccountInformationBO corporateAccountInformationBO = new CorporateAccountInformationBO();
        private IntroducingBrokerBO introducingBrokerBO = new IntroducingBrokerBO();
        private AssetManagerBO assetManagerBO = new AssetManagerBO();
        private CurrentDeskSecurity currentDeskSecurity;
        private PartnerCommissionBO partCommBO = new PartnerCommissionBO();
        private Client_AccountBO clientAccBO = new Client_AccountBO();
        private AgentBO agentBO = new AgentBO();

        public IndividualAccountModel individualAccountModel;

        #endregion

        #region Methods

        #region DEMO ACCOUNT

        /// <summary>
        /// This Function will return to DemoAccount View
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            try
            {
                //var organizationBO = new OrganizationBO();
                //var browserUrl = Request.Url.AbsoluteUri;

                ////browserUrl = "http://lmax.com"; //TODO Need to change with URL
                //var organizationID = organizationBO.GetOrganizationIDFromURL(browserUrl);

                var organizationID = OrganizationUtility.GetOrganizationID(Request.Url.AbsoluteUri);

                if (organizationID != null)
                {
                    //Add Organization ID to Session
                    SessionManagement.OrganizationID = organizationID;
                    //SessionManagement.OrganizationImagLogoHeaderURL = @"/Images/logo.png";
                    //SessionManagement.OrganizationImagLogoLoginURL =  ;
                    //SessionManagement.OrganizationImagLogoSignUpURL = ;


                    ViewData["Country"] = new SelectList(countryBO.GetCountries(), "PK_CountryID", "CountryName");
                    ViewData["AccountCurrency"] = new SelectList(accountCurrencyBO.GetSelectedCurrency(Constants.K_BROKER_DEMO, (int)organizationID),
                                                                 "PK_AccountCurrencyID", "L_CurrencyValue.CurrencyValue");
                    ViewData["AccountType"] = new SelectList(accountTypeBO.GetSelectedAccountType(Constants.K_BROKER_DEMO, (int)organizationID), "PK_AccountType",
                                                             "L_AccountTypeValue.AccountTypeValues");
                    ViewData["Initialinvestment"] = new SelectList(initialInvestmentBO.GetInitialInvestment(),
                                                                   "PK_InitialInvestmentID", "InvestmentValue");
                    ViewData["TradingPlatform"] = new SelectList(tradingPlatformBO.GetSelectedPlatform(Constants.K_BROKER_DEMO, (int)organizationID),
                                                                 "PK_TradingPlatformID",
                                                                 "L_TradingPlatformValues.TradingValue");
                    ViewData["TicketSize"] = new SelectList(ticketSizeBO.GetTickets(), "PK_TicketSizeID",
                                                            "TicketSizeValue");
                    ViewData["Language"] = new SelectList(languageBO.GetLanguages(), "PK_LanguageID", "LanguageName");
                    ViewData["TradingExp"] = new SelectList(tradingExpValuesBO.GetTradingExpValues(), "PK_ExperienceID",
                                                            "Experience");


                    return View("DemoAccount");
                }
                else
                {
                    //Return to Page Not Found Error
                    return RedirectToAction("PageNotFound", "Error");
                    //return View("ErrorMessage");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return View("ErrorMessage");
            }
        }

        /// <summary>
        /// This Function will called when user post's
        /// data from DemoAccount View.This function will insert
        /// new lead to the database.
        /// </summary>
        /// <param name="demoaccountModel"></param>
        /// <returns>ActionResult</returns>
        [HttpPost, ValidateInput(false)]
        public ActionResult Index(DemoAccountModel demoAccountModel)
        {
            try
            {
                var organizationID = SessionManagement.OrganizationID;

                if (organizationID != null)
                {
                    //Checking whether model state is valid or not
                    if (ModelState.IsValid)
                    {
                        //Creating New Demo Lead
                        var newDemoLead = new DemoLead()
                            {
                                FirstName = demoAccountModel.FirstName,
                                LastName = demoAccountModel.LastName,
                                EmailAddress = demoAccountModel.EmailAddress,
                                PhoneNo = demoAccountModel.PhoneNumber,
                                FK_ResidenceCountry = demoAccountModel.CountryCode,
                                FK_AccountTypeID = demoAccountModel.AccountType,
                                FK_AccountCurrencyID = demoAccountModel.AccountCurrency,
                                FK_PlatformID = demoAccountModel.TradingPlatform,
                                FK_InvestmentID = demoAccountModel.InitialInvestment,
                                FK_TicketSizeID = demoAccountModel.TicketSize,
                                FK_PreferedCommunicationLanguage = demoAccountModel.LanguageCode,
                                IsEnglishSpeaking = demoAccountModel.IsEnglishSpeaking,
                                FK_ExperienceID = demoAccountModel.TradingExperience,
                                IntroducingBrokerOrAgent = demoAccountModel.IntroducingBrokerOrAgent,
                                FK_OrganizationID = (int) organizationID

                            };

                        //Instantiating DemoLead Buisness Object and creating new Lead.
                        var demoLeadBO = new DemoLeadBO();
                        demoLeadBO.AddNewDemoLead(newDemoLead);

                        //returning sucessfully to the view.
                        return View("RegistartionSuccess");
                    }
                    else
                    {
                        ViewData["Country"] = new SelectList(countryBO.GetCountries(), "PK_CountryID", "CountryName");
                        ViewData["AccountCurrency"] =
                            new SelectList(accountCurrencyBO.GetSelectedCurrency(1, (int) organizationID),
                                           "PK_AccountCurrencyID", "L_CurrencyValue.CurrencyValue");
                        ViewData["AccountType"] =
                            new SelectList(accountTypeBO.GetSelectedAccountType(1, (int) organizationID),
                                           "PK_AccountType",

CurrentDesk/CurrentDesk.BackOffice/Views/AccountSignUp/CorporateAccountReview.cshtml
@model CurrentDesk.BackOffice.Models.CorporateAccountReviewModel
@{
    ViewBag.Title = "CorporateAccountReview";
}

@using (Html.BeginForm("CorporateAccountReview", "AccountSignUp", FormMethod.Post))
{
<div class="content-section">
    <div class="wrapper">
        <!-- Signup Step 3 - Review -->
        <div id="live-step-3" class="review-box">
            <h1>
                Sign Up - Review</h1>
            <div class="content-section">
                <h2>
                    Company Information</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Company Name:</label></dt>
                        <dt class="columns seven">
                            <label>
                                Company Type:</label></dt>
                        <dd class="columns five">
                            @Html.DisplayFor(model => model.CompanyName)</dd>
                        <dd class="columns seven">
                            @Html.DisplayFor(model => model.CompanyType)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns twelve">
                            <label>
                                Company Address:</label></dt>
                        <dd class="columns twelve">
                            @Html.DisplayFor(model => model.CompanyAddLine1)<br/>
                            @Html.DisplayFor(model => model.CompanyAddLine2)<br/>
                            @Html.DisplayFor(model => model.CompanyCity), @Html.DisplayFor(model => model.CompanyCountry),
                            @Html.DisplayFor(model => model.CompanyPostalCode)</dd>
                    </dl>
                </div>
                <h2>
                    Authorized Officer
                </h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns twelve">
                            <label>
                                Full Name:</label></dt>
                        <dd class="columns twelve">
                            @Html.DisplayFor(model => model.AuthOfficerTitle) @Html.DisplayFor(model => model.AuthOfficerFirstName)
                            @Html.DisplayFor(model => model.AuthOfficerMiddleName) @Html.DisplayFor(model => model.AuthOfficerLastName)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Date of Birth:</label></dt>
                        <dt class="columns seven">
                            <label>
                                Gender:</label></dt>
                        <dd class="columns five">
                            @Html.DisplayFor(model => model.AuthOfficerDobDay)/@Html.DisplayFor(model => model.AuthOfficerDobMonth)/@Html.DisplayFor(model => model.AuthOfficerDobYear)</dd>
                        <dd class="columns seven">
                            @Html.DisplayFor(model => model.AuthOfficerGender)
                        </dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Citizenship:</label></dt>
                        <dt class="columns seven">
                            <label>
                                ID Information:</label></dt>
                        <dd class="columns five">
                            @Html.DisplayFor(model => model.AuthOfficerCitizenship)</dd>
                        <dd class="columns seven">
                            @Html.DisplayFor(model => model.AuthOfficerIdInfo): @Html.DisplayFor(model => model.AuthOfficerIdNumber)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns twelve">
                            <label>
                                Country of Residence:</label></dt>
                        <dd class="columns twelve">
                            @Html.DisplayFor(model => model.AuthOfficerResidenceCountry)</dd>
                    </dl>
                </div>
                <h2>
                    Authorized Officer Contact Information</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns twelve">
                            <label>
                                Residential Address:</label></dt>
                        <dd class="columns twelve">
                            @Html.DisplayFor(model => model.AuthOfficerAddLine1)<br/>
                            @Html.DisplayFor(model => model.AuthOfficerAddLine2)<br/>
                            @Html.DisplayFor(model => model.AuthOfficerCity), @Html.DisplayFor(model => model.AuthOfficerCountry),
                            @Html.DisplayFor(model => model.AuthOfficerPostalCode)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Telephone Number:</label></dt>
                        <dt class="columns seven">
                            <label>
                                Mobile Number:</label></dt>
                        <dd class="columns five">
                            @Html.DisplayFor(model => model.AuthOfficerTelNumberCountryCode)-@Html.DisplayFor(model => model.AuthOfficerTelNumber)</dd>
                        <dd class="columns seven">
                            @Html.DisplayFor(model => model.AuthOfficerMobileNumberCountryCode)-@Html.DisplayFor(model => model.AuthOfficerMobileNumber)</dd>
                    </dl>
                </div>
                <h2>
                    Banking Information</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Bank Name:</label></dt>
                        <dt class="columns three">
                            <label>
                                Account Number:</label></dt>
                        <dt class="columns four">
                            <label>
                                Bic Number/SWIFT Code:</label></dt>
                        <dd class="columns five">
                            @Html.DisplayFor(model => model.BankName)</dd>
                        <dd class="columns three">
                            @Html.DisplayFor(model => model.AccountNumber)</dd>
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.BicOrSwiftCode)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns five">
                            <label>
                                Bank Address:</label></dt>
                        <dt class="columns seven">
                            <label>
                                Receiving Bank Information:</label></dt>
                        <dd class="columns fove">
                            @Html.DisplayFor(model => model.BankAddLine1)<br/>
                            @Html.DisplayFor(model => model.BankAddLine2)<br/>
                            @Html.DisplayFor(model => model.BankCity), @Html.DisplayFor(model => model.BankCountry),
                            @Html.DisplayFor(model => model.BankPostalCode)</dd>
                        <dd class="columns seven">
                            @Html.DisplayFor(model => model.ReceivingBankInfoId):@Html.DisplayFor(model => model.ReceivingBankInfo)
                        </dd>
                    </dl>
                </div>
                <h2>
                    Financial Information</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns four">
                            <label>
                                Estimate Annual Income?</label></dt>
                        <dt class="columns four">
                            <label>
                                Liquid Assets:</label></dt>
                        <dt class="columns four">
                            <label>
                                Total net worth in Euros:</label></dt>
                    </dl>
                    <dl class="form-list row">
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.EstimatedAnnualIncome)</dd>
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.LiquidAssets)</dd>
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.NetWorthEuros)</dd>
                    </dl>
                </div>
                <h2>
                    Trading Experience</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns four">
                            <label>
                                Do you have experience trading securities?</label></dt>
                        <dt class="columns four">
                            <label>
                                Do you have experience trading options?</label></dt>
                        <dt class="columns four">
                            <label>
                                Do you have experience trading foreign exchange?</label></dt>
                    </dl>
                    <dl class="form-list row">
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.DrpHaveExperienceTradingSecurities)</dd>
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.DrpHaveExperienceTradingOptions)</dd>
                        <dd class="columns four">
                            @Html.DisplayFor(model => model.DrpHaveExperienceTradingForeignExchange)</dd>
                    </dl>
                </div>
                <h2>
                    Other Information</h2>
                <div class="form-box">
                    <dl class="form-list row">
                        <dt class="columns six">
                            <label>
                                Do you have or have you ever held and other account with FQ Securities?</label></dt>
                        <dt class="columns six">
                            <label>
                                Have you ever been a registered person/entity with CFTC, NFA, SEC, FINRA, FSA, BaFin,
                                etc?</label></dt>
                        <dd class="columns six">
                            @Html.DisplayFor(model => model.HaveAccWithFqSecurities)</dd>
                        <dd class="columns six">
                            @Html.DisplayFor(model => model.RequiredToBeRegisteredWithRegulator)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns six">
                            <label>
                                Are you required to be registered with a regulator?</label></dt>
                        <dt class="columns six">
                            <label>
                                Are you an employee of an exchange or regulator organization?</label></dt>
                        <dd class="columns six">
                            @Html.DisplayFor(model => model.EverDeclaredBankruptcy)</dd>
                        <dd class="columns six">
                            @Html.DisplayFor(model => model.RegisteredPerson)</dd>
                    </dl>
                    <dl class="form-list row">
                        <dt class="columns twelve">
                            <label>
                                Have you ever declared bankruptcy?</label></dt>
                        <dd class="columns twelve">
                            @Html.DisplayFor(model => model.EmployeeOfExchangeOrRegulatorOperator)</dd>
                    </dl>
                </div>
                <div style="display: none">
                    @Html.EditorFor(model => model.CorporateModel)
                    @Html.EditorFor(model => model.IsLive)
                </div>
                <!-- Button Box -->
                <div class="button-box">
                    <input class="live-submit-send button submit right" type="submit" value="Submit" /></div>
            </div>
        </div>
        <!-- End Signup Step 3 - Review -->
    </div>
</div>
}

CurrentDesk/CurrentDesk.BackOffice/Views/AccountSignUp/ErrorMessage.cshtml
@{
    ViewBag.Title = "ErrorMessage";
}

<h2>There is some error in process</h2>

CurrentDesk/CurrentDesk.BackOffice/Views/AccountSignUp/RegistartionSuccess.cshtml
@{
    ViewBag.Title = "RegistrationSuccess";
}
<!-- BEGIN WRAPPER -->
<div class="wrapper">

    <!-- Header Styles -->
    <div class="header">

        <!-- Main Content Section -->
        <div class="main-content">
            <div class="wrapper">

                <!-- Begin Error Page Content -->
                <h1 class="success" style="color: green"> YOU HAVE SUCCESSFULLY REGISTERED </h1>
                <div class="content-section">
                </div>
                <!-- End Demo Account Signup Form -->

            </div>
        </div>
        <!-- End Main Content Section -->

        <div class="push"></div>
    </div>
</div>
<!-- END WRAPPER -->