CurrentDesk/CurrentDesk.BackOffice/Controllers/InboxController.cs
#region Header Information
/**************************************************************************
 * File Name     : InboxController.cs
 * Author        : Chinmoy Dey
 * Copyright     : Mindfire Solutions
 * Creation Date : 1st May 2013
 * Modified Date : 1st May 2013
 * Description   : This file contains Inbox controller and related actions
 *                 to handle Traders Inbox related functionality
 * ************************************************************************/
#endregion

#region Namespace Used
using CurrentDesk.BackOffice.Custom;
using CurrentDesk.BackOffice.Models.Inbox;
using CurrentDesk.BackOffice.Security;
using CurrentDesk.Logging;
using CurrentDesk.Repository.CurrentDesk;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
#endregion

namespace CurrentDesk.BackOffice.Controllers
{
    /// <summary>
    /// This class represents Inbox controller and related actions
    /// to handle Traders Inbox related functionality
    /// </summary>
    [AuthorizeTrader, NoCache]
    public class InboxController : Controller
    {
        #region Variables
        private InternalUserMessageBO intUsrMsgBO = new InternalUserMessageBO();
        #endregion

        /// <summary>
        /// This action returns Index view of Inbox menu
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    ViewData["UserDisplayName"] = SessionManagement.DisplayName;

                    return View();
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return View("ErrorMessage");
            }
        }

        /// <summary>
        /// This action returns list of user messages as per status
        /// </summary>
        /// <param name="status">status</param>
        /// <returns></returns>
        public ActionResult GetUserMessages(string status)
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    var lstMessages = new List<InboxModel>();
                    LoginInformation loginInfo = SessionManagement.UserInfo;

                    var sortColName = System.Web.HttpContext.Current.Request["sidx"];
                    var sortOrder = System.Web.HttpContext.Current.Request["sord"];

                    //Get all messages of user as per status
                    var userMsgs = intUsrMsgBO.GetUserMessages(loginInfo.UserID, status, sortColName, sortOrder);

                    foreach (var msg in userMsgs)
                    {
                        var userMsg = new InboxModel();
                        userMsg.PK_MessageID = msg.PK_MessageID;
                        userMsg.MessageSubject = msg.MessageSubject;
                        userMsg.MessageBody = msg.MessageContent;
                        userMsg.Timestamp = Convert.ToDateTime(msg.Timestamp).ToString("dd/MM/yyyy HH:mm:ss tt");
                        userMsg.FromUserName = msg.FromUserName;
                        userMsg.IsRead = (bool)msg.IsRead;
                        userMsg.LongDateString = Convert.ToDateTime(msg.Timestamp).ToLongDateString() + " " + Convert.ToDateTime(msg.Timestamp).ToLongTimeString();
                        userMsg.MessageTime = (DateTime)msg.Timestamp;

                        lstMessages.Add(userMsg);
                    }

                    return Json(new
                    {
                        total = 1,
                        page = 1,
                        records = lstMessages.Count,
                        rows = lstMessages
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return View("ErrorMessage");
            }
        }

        /// <summary>
        /// This action changes status of selected msg to archive
        /// </summary>
        /// <param name="pkMsgID">pkMsgID</param>
        /// <returns></returns>
        public ActionResult ArchiveSelectedMessage(string msgIDs)
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    return Json(intUsrMsgBO.ArchiveSelectedMessage(msgIDs));
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return Json(false);
            }
        }

        /// <summary>
        /// This action deletes selected message
        /// </summary>
        /// <param name="pkMsgID">pkMsgID</param>
        /// <returns></returns>
        public ActionResult DeleteSelectedMessage(string msgIds)
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    return Json(intUsrMsgBO.DeleteSelectedMessage(msgIds));
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return Json(false);
            }
        }

        /// <summary>
        /// This action sets IsRead value of a msg to true
        /// </summary>
        /// <param name="msgID">msgID</param>
        public void SetMessageIsReadTrue(int msgID)
        {
            try
            {
                intUsrMsgBO.SetMessageIsReadTrue(msgID);
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                throw;
            }
        }

        /// <summary>
        /// This action returns no. of new msg exists
        /// for user
        /// </summary>
        /// <returns></returns>
        public ActionResult CheckNewUserMessage()
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    LoginInformation loginInfo = SessionManagement.UserInfo;
                    
                    return Json(intUsrMsgBO.CheckNewUserMessage(loginInfo.UserID));
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return Json(false);
            }
        }

    }
}

CurrentDesk/CurrentDesk.BackOffice/Controllers/ProfileController.cs
#region Header Information
/********************************************************
 * File Name     : ProfileController.cs
 * Author        : Chinmoy Dey
 * Copyright     : Mindfire Solutions
 * Creation Date : 21st Jan 2013 
 * Modified Date : 21st Jan 2013
 * Description   : This file contains controller actions for profile view of different account types
 * *****************************************************/
#endregion

#region
using System.Web.Mvc;
using CurrentDesk.BackOffice.Security;
using CurrentDesk.Common;
using CurrentDesk.Repository.CurrentDesk;
using CurrentDesk.BackOffice.Models;
using System.Linq;
using System;
using System.Collections.Generic;
using CurrentDesk.Models;
using CurrentDesk.BackOffice.Models.Edit;
using System.Web;
using System.IO;
using System.Web.Script.Serialization;
using CurrentDesk.Logging;
using CurrentDesk.BackOffice.Custom;
#endregion

namespace CurrentDesk.BackOffice.Controllers
{
    /// <summary>
    /// This controller contains actions for profile view of different account types
    /// </summary>
    [AuthorizeTrader, NoCache]
    public class ProfileController : Controller
    {
        #region Variables

        private L_CountryBO countryBO = new L_CountryBO();
        private AccountTypeBO accountTypeBO = new AccountTypeBO();
        private L_InitialInvestmentBO initialInvestmentBO = new L_InitialInvestmentBO();
        private TradingPlatformBO tradingPlatformBO = new TradingPlatformBO();
        private L_TicketSizeBO ticketSizeBO = new L_TicketSizeBO();
        private AccountCurrencyBO accountCurrencyBO = new AccountCurrencyBO();
        private L_LanguagesBO languageBO = new L_LanguagesBO();
        private L_AccountCodeBO accountCodeBO = new L_AccountCodeBO();
        private DemoLeadBO demoLeadBO = new DemoLeadBO();
        private L_IDInformationTypeBO idInfoTypeBO = new L_IDInformationTypeBO();
        private L_RecievingBankBO receivingBankInfoBO = new L_RecievingBankBO();
        private L_AnnualIncomeValueBO annualIncomeValuesBO = new L_AnnualIncomeValueBO();
        private L_LiquidAssetsValueBO liquidAssetsValuesBO = new L_LiquidAssetsValueBO();
        private L_NetWorthEurosBO netWorthEurosValuesBO = new L_NetWorthEurosBO();
        private L_TradingExperienceBO tradingExpValuesBO = new L_TradingExperienceBO();
        private L_TrusteeTypeValueBO trusteeTypeValuesBO = new L_TrusteeTypeValueBO();
        private L_CompanyTypeValueBO companyTypeValuesBO = new L_CompanyTypeValueBO();
        private L_CommissionIncrementValueBO commissionIncremantValuesBO = new L_CommissionIncrementValueBO();
        private L_WidenSpreadsValueBO widenSpreadValuesBO = new L_WidenSpreadsValueBO();
        private LiveLeadBO liveLeadBO = new LiveLeadBO();
        private ClientBO clientBO = new ClientBO();
        private UserBO userBO = new UserBO();
        private IndividualAccountInformationBO individualAccountInformationBO = new IndividualAccountInformationBO();
        private CorporateAccountInformationBO corporateAccountInformationBO = new CorporateAccountInformationBO();
        private IntroducingBrokerBO introducingBrokerBO = new IntroducingBrokerBO();
        private AssetManagerBO assetManagerBO = new AssetManagerBO();
        private UserActivityBO userActivityBO = new UserActivityBO();
        private ProfileActivityBO profileActivityBO = new ProfileActivityBO();


        #endregion

        /// <summary>
        /// This actions redirects to proper profile view as per account type
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    var loginInfo = SessionManagement.UserInfo;
                    var accountType = loginInfo.AccountType;

                    //Get account type details
                    var accountTypeDetails = accountTypeBO.GetAccountTypeAndFormTypeValue(accountType);

                    if (accountTypeDetails.FK_AccountTypeValue == Constants.K_ACCT_INDIVIDUAL)
                    {
                        return RedirectToAction("IndividualProfile");
                    }
                    else if (accountTypeDetails.FK_AccountTypeValue == Constants.K_ACCT_JOINT)
                    {
                        return RedirectToAction("JointProfile");
                    }
                    else if (accountTypeDetails.FK_AccountTypeValue == Constants.K_ACCT_CORPORATE)
                    {
                        return RedirectToAction("CorporateProfile");
                    }
                    else if (accountTypeDetails.FK_AccountTypeValue == Constants.K_ACCT_TRUST)
                    {
                        return RedirectToAction("TrustProfile");
                    }
                    else
                    {
                        return View("ErrorMessage");
                    }
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception ex)
            {
                CurrentDeskLog.Error(ex.Message, ex);
                return View("ErrorMessage");
            }
        }

        /// <summary>
        /// This actions returns Individual profile view with required data
        /// </summary>
        /// <returns></returns>
        public ActionResult IndividualProfile()
        {
            try
            {
                if (SessionManagement.UserInfo != null)
                {
                    LoginInformation loginInfo = SessionManagement.UserInfo;
                    AccountNumberRuleInfo ruleInfo = SessionManagement.AccountRuleInfo;

                    ViewData["Country"] = new SelectList(countryBO.GetCountries(), "PK_CountryID", "CountryName");
                    ViewData["ReceivingBankInfo"] = new SelectList(receivingBankInfoBO.GetReceivingBankInfo((int)SessionManagement.OrganizationID), "PK_RecievingBankID", "RecievingBankName");

                    //Get Individual Account details for the user
                    var selectedClient = clientBO.GetIndividualAccountDetails(loginInfo.UserID);
                    var userInformation = selectedClient.User;
                    var clientInformations = selectedClient.IndividualAccountInformations.FirstOrDefault();
                    var bankInformationList = selectedClient.BankAccountInformations;
                    var clientAccInfo = selectedClient.Client_Account.FirstOrDefault();
                    var bankList = new List<BankAccountModel>();


                    //Assigning properties to IndividualAccountReviewModel object
                    var model = new IndividualAccountReviewModel();
                    model.Title = clientInformations.Title != null ? (clientInformations.Title == "1" ? "Mr." : "Mrs.") : "";
                    model.FirstName = clientInformations.FirstName ?? "";
                    model.MiddleName = clientInformations.MiddleName ?? "";
                    model.LastName = clientInformations.LastName ?? "";
                    model.DobMonth = Convert.ToDateTime(clientInformations.BirthDate).Month.ToString("D2");
                    model.DobDay = Convert.ToDateTime(clientInformations.BirthDate).Day.ToString("D2");
                    model.DobYear = Convert.ToDateTime(clientInformations.BirthDate).Year;
                    model.Gender = clientInformations.Gender != null ? (clientInformations.Gender == true ? "Male" : "Female") : "";
                    model.Citizenship = clientInformations.FK_CitizenShipCountryID != null ? countryBO.GetSelectedCountry((int)clientInformations.FK_CitizenShipCountryID) : "";
                    model.IdInfo = clientInformations.FK_IDInformationID != null ? idInfoTypeBO.GetSelectedIDInformation((int)clientInformations.FK_IDInformationID) : "";
                    model.IdNumber = clientInformations.IDNumber != null ? clientInformations.IDNumber : "";
                    model.ResidenceCountry = countryBO.GetSelectedCountry((int)clientInformations.FK_ResidenceCountryID);
                    model.ClientAccountNumber = clientAccInfo != null ? clientAccInfo.LandingAccount.Split('-')[ruleInfo.AccountNumberPosition - 1] : "";
                    model.PhoneID = clientInformations.PhoneID ?? "";

                    model.ResidentialAddLine1 = clientInformations.ResidentialAddress != null ? (clientInformations.ResidentialAddress.Split('@')[0] + " " + clientInformations.ResidentialAddress.Split('@')[1]) : "";
                    model.ResidentialCity = clientInformations.ResidentialAddressCity ?? "";
                    model.ResidentialCountry = clientInformations.FK_ResidentialAddressCountryID != null ? countryBO.GetSelectedCountry((int)clientInformations.FK_ResidentialAddressCountryID) : "";
                    model.ResidentialPostalCode = clientInformations.ResidentialAddressPostalCode ?? "";
                    model.YearsInCurrentAdd = clientInformations.MonthsAtCurrentAddress != null ? (int)(clientInformations.MonthsAtCurrentAddress / 12) : 0;
                    model.MonthsInCurrentAdd = clientInformations.MonthsAtCurrentAddress != null ? (int)(clientInformations.MonthsAtCurrentAddress % 12) : 0;
                    model.PreviousAddLine1 = clientInformations.PreviousAddress != null ? (clientInformations.PreviousAddress.Split('@')[0] + " " + clientInformations.PreviousAddress.Split('@')[1]) : "";
                    model.PreviousCity = clientInformations.PreviousAddressCity ?? "";
                    model.PreviousCountry = clientInformations.FK_PreviousAddressCounrtyID != null ? countryBO.GetSelectedCountry((int)clientInformations.FK_PreviousAddressCounrtyID) : "";
                    model.PreviousPostalCode = clientInformations.PreviousAddressPostalCode ?? "";

CurrentDesk/CurrentDesk.BackOffice/Views/Shared/BackOfficeMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>FastQuote - Back Office</title>

    <meta name="title" content="FastQuote Back Office">
    <meta name="author" content="CurrentDesk">
    <meta name="Copyright" content="Copyright CurrentDesk 2013. All Rights Reserved.">
    <meta name="DC.title" content="FastQuote Back Office">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    @*<link rel="shortcut icon" href="img/favicon.ico">*@
    @*<link rel="stylesheet" href="css/style.css">*@

    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/commonStyle")
    <script src="~/Scripts/Profile/BankingCommon.js"></script>
</head>
<body>
    <div class="wrapper">
        <!-- BEGIN HEADER SECTION -->
        <header>

            <!-- Universal Top Bar Section -->
            <div class="top-bar">
                <!-- Client Logo with link to dashboard -->
                <h1><a class="logo" href="#">
                    <img src ="@Url.Action("GetHeaderImage","Account")" />
                    </a></h1>
                <!-- Notifications section -->
                <div class="notifications"><a href="#" class="alert-linkMain"><span class="icon"></span><span class="alert">3</span>Notifications</a></div>
                <!-- User and logout information -->
                <div class="top-right">
                    @*<img class="avatar"  src="@HttpContext.Current.Session["ImageURl"]" onerror="imgError(this);" alt=""><span class="user">@HttpContext.Current.Session["UserEmail"]</span><a class="logout" href="@Url.Action("LogOff", "Account")">Exit</a></div>*@
                    <img class="avatar"  src="@CurrentDesk.BackOffice.Security.SessionManagement.ImageURL" onerror="imgError(this);" alt="">
                    <span class="user">@CurrentDesk.BackOffice.Security.SessionManagement.DisplayName</span><a class="logout" href="@Url.Action("LogOff", "Account")">Exit</a>
                </div>
            </div>

            <!-- Universal Top Navigation Section -->
            <nav class="top-nav">
                <ul class="clearfix">
                    <!-- The first <li> needs the class .first and is only here for styling purposes. No links should be added inside. -->
                    <li class="first"><span></span></li>
                    <li id="liDashboard"><a class="dashboard" href="@Url.Action("Index", "Dashboard")">Dashboard</a></li>
                    <li id="liMyAccount"><a class="accounts" href="@Url.Action("Index", "MyAccount")">My Accounts</a></li>
                    <li id="liFundTransfer"><a class="transfers" href="@Url.Action("FundAccount", "FundTransfer")">Transfers</a></li>
                    <li id="liDocument"><a class="documents" href="@Url.Action("Index", "Document")">Documents</a></li>
                    <li id="liReports"><a class="reports" href="@Url.Action("Index", "Reports")">Reports</a></li>
                    <li id="clientProfile"><a class="profile" href="@Url.Action("Index", "Profile")">Profile</a></li>
                    <li id="liInbox"><a class="inbox" href="@Url.Action("Index", "Inbox")">Inbox</a></li>
                    <li><a class="portal" href="#">AM Portal</a></li>
                    <!-- The last <li> needs the class .last and is only here for styling purposes. No links should be added inside. -->
                    <li class="last"><span></span></li>
                </ul>
            </nav>

        </header>
        <!-- END HEADER SECTION -->

        @RenderBody()

        <!-- BEGIN FOOTER SECTION -->
        <footer>
            <div class="left">
                <p class="copyright">
                    &copy; Copyright 2013 by CurrentDesk, Inc.<br>
                    All Rights Reserved.
                </p>
            </div>
            <div class="right"><span class="phone">1.888.349.2323</span><a class="help" href="#">Help</a></div>
        </footer>
        <!-- END FOOTER SECTION -->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: true)
    <!-- Grab Google CDN's jQuery. fall back to local if necessary -->

    <div id="loading" class="loading-wrapper" style="display: none;"></div>
    
    <!-- BEGIN NOTIFICATIONS SECTION -->
    <div id="alertBox" class="alert-link alert-box">
        <img class="top-arrow" src="/Images/notifications-arrow.png">
        <div class="alert-box-wrapper">
            <div class="scroll-table">
                <table>
                    <tbody>
                        <tr class="header-row">
                            <td colspan="2"><i class="icon-envelope icon-white"></i>MESSAGES</td>
                        </tr>
                        <tr>
                            <td><i>You have <b><span id="spnNewMsgCount">0</span></b> unread messages.</i></td>
                            <td class="text-center width-80"><a class="btn btn-small" href="@Url.Action("Index", "Inbox")">View All</a></td>
                        </tr>
                        <tr class="header-row yellow">
                            <td colspan="2"><i class="icon-flag"></i>SYSTEM NOTIFICATIONS</td>
                        </tr>
                        <tr class="yellow-light">
                            <td>We will be upgrading the system on Saturday between the hours of 01:00 - 03:00 GMT asdf asdf asdf asdfas df</td>
                            <td class="text-center width-80"><a class="btn btn-small" href="#"><i class="icon-remove"></i></a></td>
                        </tr>
                        <tr class="yellow-light">
                            <td>We will be upgrading the system on Saturday between the hours of 01:00 - 03:00 GMT asdf asdf asdf asdfas df</td>
                            <td class="text-center width-80"><a class="btn btn-small" href="#"><i class="icon-remove"></i></a></td>
                        </tr>
                        <tr class="header-row red">
                            <td colspan="2"><i class="icon-warning-sign icon-white"></i>&nbsp;ALERTS</td>
                        </tr>
                        <tr class="red-light">
                            <td>[Asset Mananger] has requested [Amount] [Cur] be transferred from [Account #] to [Account #].</td>
                            <td class="text-center width-80"><a class="btn btn-small" href="#"><i class="icon-ok"></i></a><a class="btn btn-small" href="#"><i class="icon-remove"></i></a></td>
                        </tr>
                        <tr class="red-light">
                            <td>You have requested a leverage increase [Leverage] on account [Account #].  Please confirm you understand the risk involved with increased leverage, or contact a support member for more details.</td>
                            <td class="text-center width-80"><a class="btn btn-small" href="#"><i class="icon-ok"></i></a><a class="btn btn-small" href="#"><i class="icon-remove"></i></a></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- END MODAL CONTENT SECTION -->

</body>
</html>

<script type="text/javascript">

    //Display notification div
    $(".alert-linkMain").click(function () {
        $("#alertBox").toggle();
        $("#alertBox").animate({ top: '54', opacity: 100 }, 100);
        return false
    });

    //Check for new user messages every 5 secs and display in notification
    setInterval(function () {
        $.post("@Url.Action("CheckNewUserMessage", "Inbox")", function (data) {
            if (data != null && data != undefined) {
                $('#spnNewMsgCount').text(data);
            }
        });
    }, 5000);

</script>

CurrentDesk/CurrentDesk.BackOffice/Views/Shared/ErrorMessage.cshtml
@{
    ViewBag.Title = "Error";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- BEGIN WRAPPER -->
<div class="wrapper">

    <!-- Header Styles -->
    <div class="header">

        <!-- Main Content Section -->
        <div class="main-content">
            <div class="wrapper">

                <!-- Begin Error Page Content -->
                <h1 class="error">ERROR IN PROCESSING REQUEST</h1>
                <div class="content-section">
                </div>
                <!-- End Demo Account Signup Form -->

            </div>
        </div>
        <!-- End Main Content Section -->

        <div class="push"></div>
    </div>
</div>
<!-- END WRAPPER -->

CurrentDesk/CurrentDesk.BackOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />    
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic|PT+Sans+Narrow:700" />  
    
    
     
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
            @*<div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Demo", "Index", "AccountSignUp")</li>
                            <li>@Html.ActionLink("Live Account", "LiveAccountInitial", "AccountSignUp")</li>
                            <li>@Html.ActionLink("Become A Partner", "PartnersAccountInitial", "AccountSignUp")</li>
                        </ul>
                    </nav>
                </div>
            </div>*@
           @* <div class="header"><img src="~/Images/logo.png" alt="FastQuote Securities" /></div>*@
            <div class="header"><img src="@Url.Action("GetSignUpImage", "AccountSignUp")" alt="FastQuote Securities" /></div>
        </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
    </div>
    <footer>
           <!-- Footer Section -->
<div class="footer">
	
	<!-- Disclamer Section -->
	<div class="disclaimer">
		<div class="wrapper">
			<h2>&copy; Copyright 2013. All Rights Reserved. Powered by CurrentDesk.</h2>
			<p><strong>HIGH RISK WARNING:</strong> Foreign exchange trading carries a high level of risk that may not be suitable for all investors. Leverage creates additional risk and loss exposure. Before you decide to trade foreign exchange, carefully consider your investment objectives, experience level, and risk tolerance. You could lose some or all of your initial investment; do not invest money that you cannot afford to lose. Educate yourself on the risks associated with foreign exchange trading, and seek advice from an independent financial or tax advisor if you have any questions.</p>
			<p><strong>ADVISORY WARNING:</strong> FQ Securities provides references and links to selected blogs and other sources of economic and market information as an educational service to its clients and prospects and does not endorse the opinions or recommendations of the blogs or other sources of information. Clients and prospects are advised to carefully consider the opinions and analysis offered in the blogs or other information sources in the context of the client or prospect’s individual analysis and decision making. None of the blogs or other sources of information is to be considered as constituting a track record. Past performance is no guarantee of future results and FQ Securities specifically advises clients and prospects to carefully review all claims and representations made by advisors, bloggers, money managers and system vendors before investing any funds or opening an account with any Forex dealer. Any news, opinions, research, data, or other information contained within this website is provided as general market commentary and does not constitute investment or trading advice. FQ Securities expressly disclaims any liability for any lost principal or profits without limitation which may arise directly or indirectly from the use of or reliance on such information. As with all such advisory services, past results are never a guarantee of future results.</p>
		</div>
	</div>
	
</div>
<!-- End Footer Section -->
        </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/uniform")
    @RenderSection("scripts", required: false) 
</body>
</html>